#!/bin/sh

HOME=/var/local/nonametv
export HOME

R=/var/local/nonametv/nonametv-logos

cd $R
git pull

rm -rf build
mkdir -p $R/build $R/build/44x44 $R/build/16x16
mkdir -p $R/upload

cd $R/build
cp -a $R/100x100/*.png .

# Generate smaller versions of all 100x100-images
for f in *.png
do
  convert -resize 44x44 $f 44x44/$f
  convert -resize 16x16 $f 16x16/$f
done

cd $R

# Override the smaller images with any hand-crafted versions:
cp 44x44/*.png build/44x44/
cp 16x16/*.png build/16x16/

rsync -c --delete -r build/ upload/

# sitecopy -r /var/local/nonametv/sitecopyrc --list logos.swedb.se
sitecopy -r /var/local/nonametv/sitecopyrc --update logos.swedb.se
rsync -av --delete $R/upload/ acheron.geijersson.com:public_html/chanlogos/
rsync -av --delete $R/upload/ fiorina161.geijersson.com:public_html/chanlogos/
rsync -av --delete $R/upload/ xmltv3.tvsajten.com:xmltv/chanlogos/


